"""Dataclasses del dominio."""

from mukuwareru.nucleo.modelos.entidades import (
    Anotacion,
    AristaGrafo,
    BloquePlan,
    Cuaderno,
    DestinoNodo,
    DestinoVinculo,
    Documento,
    EstadoNodo,
    Etiqueta,
    Evaluacion,
    Hito,
    LineaEvaluacion,
    Materia,
    Modulo,
    NodoGrafo,
    Nota,
    OrigenSesion,
    Prioridad,
    Proyecto,
    Seccion,
    Sesion,
    TipoAnotacion,
    TipoHito,
    TipoSesion,
    Vinculo,
)

__all__ = [
    "Anotacion",
    "AristaGrafo",
    "BloquePlan",
    "Cuaderno",
    "DestinoNodo",
    "DestinoVinculo",
    "Documento",
    "EstadoNodo",
    "Etiqueta",
    "Evaluacion",
    "Hito",
    "LineaEvaluacion",
    "Materia",
    "Modulo",
    "NodoGrafo",
    "Nota",
    "OrigenSesion",
    "Prioridad",
    "Proyecto",
    "Seccion",
    "Sesion",
    "TipoAnotacion",
    "TipoHito",
    "TipoSesion",
    "Vinculo",
]
